name: CI with Dependency Cache

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache dependencies (cache-10d0889)
        id: cache-step
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/pip
            ~/.virtualenvs
          key: cache-10d0889

      - name: prime-cache-10d0889
        run: echo "Cache hit"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
